# .NET Desktop

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: CmdLine@2
  inputs:
    script: 'powershell "add-appxpackage -path Microsoft.DesktopAppConverter_2.1.4.0_x64__8wekyb3d8bbwe.Appx"
      
      echo Use the environment variables input below to pass secret variables to this script'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    failOnStderr: true
    script: '# Write your powershell commands here.
      
    
     ls 

      # Use the environment variables input below to pass secret variables to this script.'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    failOnStderr: true
    script: '# Write your powershell commands here.
      
    
     add-appxpackage -path Microsoft.DesktopAppConverter_2.1.4.0_x64__8wekyb3d8bbwe.Appx

      # Use the environment variables input below to pass secret variables to this script.'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    failOnStderr: true
    script: '# Write your powershell commands here.
    failOnStderr: false
      
    
     add-appxpackage -path Microsoft.DesktopAppConverter_2.1.4.0_x64__8wekyb3d8bbwe.Appx

      # Use the environment variables input below to pass secret variables to this script.'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    failOnStderr: true
    script: '# Write your powershell commands here.
      
    Get-Appxpackage 
     

      # Use the environment variables input below to pass secret variables to this script.'

- task: BatchScript@1
  inputs:
    filename: D:\a\1\s\1.cmd
    arguments: 

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '# Write your powershell commands here.
      
    
     DesktopAppConverter.exe -Installer \FileStar.msi -Destination Appx05 -PackageName "FileStarAB.FileStar"  -Publisher "CN=D28B8226-1360-495A-AAFF-0C4B08FC4276" -PackagePublisherDisplayName "FileStar AB" -PackageDisplayName  "FileStar" -Version 1.0.14.0 -MakeAppx -Verbose

      # Use the environment variables input below to pass secret variables to this script.'

- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
