# .NET Desktop
- task: CmdLine@2
  inputs:
    script: 'echo Write your commands here
      
      echo Use the environment variables input below to pass secret variables to this script'

trigger:
- master

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  inputs:
    filePath: 'convert.ps1'


    
