# .NET Desktop

trigger:
- master

pool:
  vmImage: 'CONSTANT-DEVELO'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: PowerShell@2
  inputs:
    filePath: 'convert.ps1'


    
