# .NET Desktop

trigger:
- master

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  inputs:
    script: 
      dir
      echo Use the environment variables input below to pass secret variables to this script'
- task: PowerShell@2
  inputs:
    filePath: 'convert.ps1'


    
