# .NET Desktop

trigger:
- master

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


- task: PowerShell@2
  inputs:
    filePath: 'convert.ps1'


    
